name: flutter_bloc_template
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  get_it: ^7.2.0
  logger: ^2.0.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  flutter_bloc: ^8.1.2
  flutter:
    sdk: flutter
  isar: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
